USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'FACSQL2') 
	DROP DATABASE FACSQL2
GO
CREATE DATABASE FACSQL2
GO

USE FACSQL2
GO

CREATE TABLE MAE_EMIDOCELE(
	NID_EMIDOCELE INT IDENTITY(1,1) NOT NULL,
	NU_EMINUMRUC VARCHAR(11),
	NO_EMIRAZSOC VARCHAR(50),
	CO_EMICODAGE CHAR(4),
	NO_ESTEMIELE VARCHAR(30),
	NO_CONEMIELE VARCHAR(50),
	NO_EMIUBIGEO CHAR(6),
	NO_EMIDEPART VARCHAR(50),
	NO_EMIPROVIN VARCHAR(50),
	NO_EMIDISTRI VARCHAR(50),
	NO_EMIDIRFIS VARCHAR(500),
	NO_BASTIPBAS VARCHAR(50),
	NO_BASNOMSRV VARCHAR(150),
	NO_BASNOMBAS VARCHAR(50),
	NO_BASUSRBAS VARCHAR(50),
	NO_BASUSRPAS VARCHAR(100),
	NO_TABFACCAB VARCHAR(50),
	NO_TABFACDET VARCHAR(50),
	NO_RUTCERDIG VARCHAR(800),
	NO_USUSOLSUN VARCHAR(500),
	NO_PASSOLSUN VARCHAR(500),
	NID_CFGSEREMI INT,
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_EMIDOCELE_NID_EMIDOCELE PRIMARY KEY (NID_EMIDOCELE),
)
GO

CREATE TABLE MAE_CFGSEREMI(
	NID_CFGSEREMI INT IDENTITY(1,1),
	CO_IDENTIFICA VARCHAR(100),
	NO_IDENTIFICA VARCHAR(100),
	CO_DOCTIPDOC CHAR(2),
	CO_DOCPREFIJ CHAR(2),
	NU_DOCFORMAT INT,
	NU_DOCINICIA INT,
	NU_DOCFINALI INT,
	NU_DOCACTUAL INT,
	NID_EMIDOCELE INT,
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_CFGSEREMI_NID_CFGSEREMI PRIMARY KEY (NID_CFGSEREMI),
	CONSTRAINT FK_CFGSEREMI_EMIDOCELE_NID_EMIDOCELE FOREIGN KEY (NID_EMIDOCELE) REFERENCES MAE_EMIDOCELE(NID_EMIDOCELE)
)
GO

CREATE TABLE TBL_DOCELECAB(
	NID_DOCELECAB INT IDENTITY(1,1) NOT NULL,
	NU_DOCSERSUN VARCHAR(10),
	NU_DOCNUMSUN VARCHAR(10),
	FE_DOCFECEMI DATETIME,
	HO_DOCHOREMI CHAR(8),
	CO_DOCTIPDOC CHAR(2),
	CO_DOCTIPMND CHAR(3),
	FE_DOCFECVEN DATETIME,
	CO_EMITIPDOC CHAR(1),
	NU_EMINUMRUC VARCHAR(11),
	NO_EMINOMCOM VARCHAR(1500),
	NO_EMIRAZSOC VARCHAR(1500),
	NO_EMIDOMDIR VARCHAR(200),
	NO_EMIDOMURB VARCHAR(25),
	NO_EMIDOMPRV VARCHAR(30),
	CO_EMIDOMUBI CHAR(6),
	NO_EMIDOMDEP VARCHAR(30),
	NO_EMIDOMDIS VARCHAR(30),
	CO_EMIDOMPAI CHAR(2),
	FL_VENTAITIN CHAR(1),
	NO_ITNDIRCOM VARCHAR(200),
	NO_ITNURBANI VARCHAR(25),
	NO_ITNPROVIN VARCHAR(30),
	CO_ITNCODUBI CHAR(6),
	NO_ITNDEPART VARCHAR(30),
	NO_ITNDISTRI VARCHAR(30),
	CO_ITNCODPAI CHAR(2),
	FL_VENTAEXPO CHAR(1),
	CO_EXPCODPAI CHAR(2),
	CO_EMICODANE CHAR(4),
	CO_RECTIPDOC CHAR(1),
	NU_RECNUMDOC VARCHAR(15),
	NO_RECRAZSOC VARCHAR(1500),
	CO_REMTIPDOC CHAR(2),
	NU_REMNUMDOC VARCHAR(30),
	FL_REFADIDOC CHAR(1),
	MT_TOTMONIMP DECIMAL(12,2),
	MT_TOTVENEXP DECIMAL(12,2),
	MT_TOTIMPEXP DECIMAL(12,2),
	CO_CODTRIEXP CHAR(4),
	MT_TOTVENINA DECIMAL(12,2),
	MT_TOTIMPINA DECIMAL(12,2),
	CO_CODTRIINA CHAR(4),
	MT_TOTVENEXO DECIMAL(12,2),
	MT_TOTIMPEXO DECIMAL(12,2),
	CO_CODTRIEXO CHAR(4),
	MT_TOTVENGRA DECIMAL(12,2),
	MT_TOTIMPGRA DECIMAL(12,2),
	CO_CODTRIGRA CHAR(4),
	MT_TOTVENGRV DECIMAL(12,2),
	MT_TOTIMPGRV DECIMAL(12,2),
	CO_CODTRIGRV CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_TOTMONISC DECIMAL(12,2),
	FL_CARGODESC VARCHAR(5),
	CO_CODCARDES CHAR(2),
	PO_CARDESPRC DECIMAL(12,5),
	MT_MONCARDES DECIMAL(12,2),
	MT_CARDESBAS DECIMAL(12,2),
	MT_TOTMONDES DECIMAL(12,2),
	MT_TOTMONCAR DECIMAL(12,2),
	MT_TOTIMPORT DECIMAL(12,2),
	MT_TOTVALVEN DECIMAL(12,2),
	MT_TOTPREVEN DECIMAL(12,2),
	CO_ADILEYEND CHAR(4),
	TX_ADIDESLEY VARCHAR(200),
	CO_ADITIPOPE CHAR(4),
	FL_PERCEPCIO CHAR(1),
	NO_PERINCADE VARCHAR(5),
	CO_PERREASON CHAR(2),
	PO_PERPORAPL DECIMAL(12,5),
	MT_PERMONPER DECIMAL(12,2),
	MT_PERBASIMP DECIMAL(12,2),
	FL_ANTICIPOS CHAR(1),
	MT_TOTMONANT DECIMAL(12,2),
	CO_GUIARUBIG CHAR(6),
	NO_GUIARDIRE VARCHAR(200),
	NO_GUIARURBA VARCHAR(25),
	NO_GUIARPROV VARCHAR(30),
	NO_GUIARDEPA VARCHAR(30),
	NO_GUIARDIST VARCHAR(30),
	CO_GUIARPAIS CHAR(2),
	FL_DETRACCIO CHAR(1),
	CO_DTRCODBIE CHAR(3),
	NO_DTRCUEBAN VARCHAR(100),
	MT_DTRMONDTR DECIMAL(12,2),
	PO_DTRPRCDTR DECIMAL(12,5),
	CO_SUNESTENV CHAR(2),
	TX_SUNRESENV VARCHAR(8000),
	FL_SUNDOCXML CHAR(1),
	XM_SUNDOCXML VARCHAR(MAX),
	FL_SUNDOCPDF CHAR(1),
	B6_SUNDOCPDF VARCHAR(MAX),
	FL_SUNDOCCDR CHAR(1),
	B6_SUNDOCCDR VARCHAR(MAX),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DOCELECAB_NID_DOCELECAB PRIMARY KEY (NID_DOCELECAB)
)
GO

CREATE TABLE INT_DOCELECAB(
	[FA1_CRUCEMI] [char](11) NOT NULL,
	[FA1_CCODSUC] [char](4) NOT NULL,
	[FA1_CTIPDOC] [char](2) NOT NULL,
	[FA1_CSERDOC] [char](4) NOT NULL,
	[FA1_CNUMDOC] [char](11) NOT NULL,
	[FA1_DFECDOC] [char](8) NOT NULL,
	[FA1_DFECVEN] [char](8) NOT NULL,
	[FA1_CCODCLI] [varchar](18) NOT NULL,
	[FA1_CNOMCLI] [varchar](80) NULL,
	[FA1_CRUCCLI] [varchar](18) NOT NULL,
	[FA1_CDIRCLI] [varchar](160) NULL,
	[FA1_CFORVEN] [nchar](5) NOT NULL,
	[FA1_CCODVEN] [nchar](5) NOT NULL,
	[FA1_CCODVE2] [nchar](5) NOT NULL,
	[FA1_CTGDORE] [char](2) NOT NULL,
	[FA1_CSEDORE] [char](4) NOT NULL,
	[FA1_CNUDORE] [varchar](20) NOT NULL,
	[FA1_CTGDOR2] [char](2) NOT NULL,
	[FA1_CNUDOR2] [varchar](20) NOT NULL,
	[FA1_CTIPOPE] [char](2) NOT NULL,
	[FA1_CCODALM] [char](4) NOT NULL,
	[FA1_CCENCOS] [char](12) NULL,
	[FA1_CGLOSA1] [varchar](100) NOT NULL,
	[FA1_CGLOSA2] [varchar](100) NOT NULL,
	[FA1_CCODMON] [char](2) NOT NULL,
	[FA1_NTIPCAM] [numeric](9, 3) NOT NULL,
	[FA1_NIMPORT] [numeric](15, 2) NOT NULL,
	[FA1_NPORDE1] [numeric](5, 2) NOT NULL,
	[FA1_NPORDE2] [numeric](5, 2) NOT NULL,
	[FA1_NPORDE3] [numeric](5, 2) NOT NULL,
	[FA1_CDIRECC] [char](80) NULL,
	[FA1_CDEBHAB] [char](1) NOT NULL,
	[FA1_CSTOCK] [char](1) NOT NULL,
	[FA1_CESTADO] [char](1) NOT NULL,
	[FA1_CUSUCRE] [char](10) NOT NULL,
	[FA1_DFECCRE] [char](8) NULL,
	[FA1_CUSUMOD] [char](10) NOT NULL,
	[FA1_DFECMOD] [char](8) NULL,
	[FA1_CDOCORI] [char](2) NOT NULL,
	[FA1_CDOCATE] [char](2) NOT NULL,
	[FA1_CCODUBI] [char](8) NOT NULL,
	[FA1_CTGPAIS] [char](5) NOT NULL,
	[FA1_CSUDORE] [char](4) NOT NULL,
	[FA1_CSUCATE] [char](4) NOT NULL,
	[FA1_CNUMATE] [char](15) NOT NULL,
	[FA1_CHORCRE] [char](5) NOT NULL,
	[FA1_CHORMOD] [char](5) NOT NULL,
	[FA1_CDIRFIS] [varchar](160) NULL,
	[FA1_CORTSUC] [char](4) NOT NULL,
	[FA1_CORTTAL] [char](4) NOT NULL,
	[FA1_CORTNUM] [char](11) NOT NULL,
	[FA1_CCODCAJ] [char](4) NOT NULL,
	[FA1_CFLACAN] [char](1) NOT NULL,
	[FA1_CTGDOR3] [char](2) NOT NULL,
	[FA1_CNUDOR3] [varchar](20) NOT NULL,
	[FA1_CFLAMAS] [char](1) NOT NULL,
	[FA1_NIMPPER] [numeric](13, 2) NOT NULL,
	[FA1_NPORPER] [numeric](10, 2) NOT NULL,
	[FA1_CFLACCT] [char](1) NOT NULL,
	[FA1_CORTVEH] [char](18) NOT NULL,
	[FA1_DFECPRO] [char](8) NOT NULL,
	[FA1_NPORIGV] [numeric](4, 2) NOT NULL,
	[FA1_CCODTRA] [char](8) NOT NULL,
	[FA1_CNOMTRA] [varchar](50) NOT NULL,
	[FA1_CCODVEH] [char](8) NOT NULL,
	[FA1_CCODFER] [char](8) NOT NULL,
	[FA1_DFECREF] [char](8) NOT NULL,
	[FA1_CCODDIR] [char](4) NOT NULL,
	[FA1_CTIPMOV] [char](1) NOT NULL,
	[FA1_CGLOSA3] [varchar](50) NOT NULL,
	[FA1_CDEPORI] [varchar](6) NOT NULL,
	[FA1_CDEPDES] [varchar](6) NOT NULL,
	[FA1_CCODPER] [char](8) NOT NULL,
	[FA1_CKEYINT] [char](17) NOT NULL,
	[EXISTE] [char](1) NULL,
	[NUEVO] [char](7) NULL,
	[FA1_CCODSUR] [varchar](4) NOT NULL,
	[FA1_NPERCMN] [numeric](13, 2) NOT NULL,
	[FA1_NPERCUS] [numeric](13, 2) NOT NULL,
	[FA1_NNUMIMP] [numeric](3, 0) NOT NULL,
	[FA1_CFLADET] [char](1) NOT NULL,
	[FA1_CFLAANT] [char](1) NOT NULL,
	[FA1_NIMPANT] [numeric](15, 2) NOT NULL,
	[FA1_NSALANT] [numeric](15, 2) NOT NULL,
	[FA1_CCODREF] [char](8) NOT NULL,
	[FA1_CDATADI] [varchar](12) NOT NULL,
	[FA1_CCODCOB] [varchar](8) NOT NULL,
	[FA1_CCODSUB] [char](4) NOT NULL,
	[FA1_CCOMPRO] [char](8) NOT NULL,
	[FA1_CANOCOM] [char](4) NOT NULL,
	[FA1_DFECANU] [char](8) NOT NULL,
	[FA1_CCODDET] [char](5) NOT NULL,
	[FA1_NPORTAS] [numeric](12, 2) NOT NULL,
	[FA1_CMONANT] [char](3) NOT NULL,
	[FA1_NSUMAPL] [numeric](15, 2) NOT NULL,
	[FA1_COD_ESTADO_SUNAT] [int] NULL,
	[FA1_MENSAJE_SUNAT] [varchar](500) NULL,
	[FA1_ESTADO_ENVIO] [int] NULL,
	[FA1_XML] [varchar](250) NULL,
	[FA1_CDR] [varchar](250) NULL,
	[FA1_PDF] [varchar](250) NULL,
	[FA1_DFECDOC9] [datetime] NULL
 CONSTRAINT [PK_INTDOCELECAB] PRIMARY KEY CLUSTERED 
(
	[FA1_CRUCEMI] ASC,
	[FA1_CCODSUC] ASC,
	[FA1_CTIPDOC] ASC,
	[FA1_CSERDOC] ASC,
	[FA1_CNUMDOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE INT_DOCELEDET(
	[FA2_CRUCEMI] [char](11) NOT NULL,
	[FA2_CCODSUC] [char](4) NOT NULL,
	[FA2_CTIPDOC] [char](2) NOT NULL,
	[FA2_CSERDOC] [char](4) NOT NULL,
	[FA2_CNUMDOC] [char](11) NOT NULL,
	[FA2_CITEM] [char](4) NOT NULL,
	[FA2_CCODART] [char](25) NOT NULL,
	[FA2_CNOMART] [char](60) NOT NULL,
	[FA2_CUNIART] [nchar](3) NOT NULL,
	[FA2_NCANTID] [numeric](13, 3) NOT NULL,
	[FA2_NPRECIO] [numeric](18, 9) NOT NULL,
	[FA2_NPREUNI] [numeric](18, 9) NOT NULL,
	[FA2_NPRUNMN] [numeric](18, 9) NOT NULL,
	[FA2_NPRUNUS] [numeric](18, 9) NOT NULL,
	[FA2_NPRSIGV] [numeric](18, 9) NOT NULL,
	[FA2_CCODALM] [char](8) NOT NULL,
	[FA2_CCODMON] [char](2) NOT NULL,
	[FA2_NTIPCAM] [numeric](7, 3) NOT NULL,
	[FA2_NPORDE1] [numeric](5, 2) NOT NULL,
	[FA2_NIMPDE1] [numeric](12, 2) NOT NULL,
	[FA2_NPORDE2] [numeric](5, 2) NOT NULL,
	[FA2_NIMPDE2] [numeric](10, 2) NOT NULL,
	[FA2_NPORDE3] [numeric](5, 2) NOT NULL,
	[FA2_NIMPDE3] [numeric](10, 2) NOT NULL,
	[FA2_NTOTDES] [numeric](10, 2) NOT NULL,
	[FA2_NPORIGV] [numeric](5, 2) NOT NULL,
	[FA2_NIMPIGV] [numeric](13, 2) NOT NULL,
	[FA2_NIMPORT] [numeric](13, 2) NOT NULL,
	[FA2_NIMPOMN] [numeric](13, 2) NOT NULL,
	[FA2_NIMPOUS] [numeric](13, 2) NOT NULL,
	[FA2_NIIGVMN] [numeric](13, 2) NULL,
	[FA2_NIIGVUS] [numeric](13, 2) NULL,
	[FA2_CSTOCK] [char](1) NOT NULL,
	[FA2_CESTADO] [char](1) NOT NULL,
	[FA2_CUSUCRE] [char](10) NOT NULL,
	[FA2_DFECCRE] [char](8) NULL,
	[FA2_CUSUMOD] [char](10) NOT NULL,
	[FA2_DFECMOD] [char](8) NULL,
	[FA2_NCOSTMN] [numeric](18, 9) NOT NULL,
	[FA2_NCOSTUS] [numeric](18, 9) NOT NULL,
	[FA2_NCANATE] [numeric](13, 3) NOT NULL,
	[FA2_CDOCATE] [char](2) NOT NULL,
	[FA2_CSUCATE] [char](4) NOT NULL,
	[FA2_CNUMATE] [char](15) NOT NULL,
	[FA2_CFLAKIT] [char](1) NOT NULL,
	[FA2_CCODCAJ] [char](4) NOT NULL,
	[FA2_NPORPER] [numeric](10, 2) NOT NULL,
	[FA2_NIMPPER] [numeric](13, 2) NOT NULL,
	[FA2_NPERCMN] [numeric](13, 2) NOT NULL,
	[FA2_NPERCUS] [numeric](13, 2) NOT NULL,
	[FA2_CCODAR2] [varchar](25) NOT NULL,
	[FA2_CALMREF] [char](4) NOT NULL,
	[FA2_CFLAATE] [char](1) NOT NULL,
	[FA2_NPESART] [numeric](10, 2) NOT NULL,
	[EXISTE] [char](1) NULL,
	[NUEVO] [char](7) NULL,
	[FA2_NCANBUL] [numeric](5, 0) NOT NULL,
	[FA2_NPESBUL] [numeric](10, 2) NOT NULL,
	[FA2_NCANTI2] [numeric](16, 6) NOT NULL,
	[FA2_NCANTI3] [numeric](13, 3) NOT NULL,
	[FA2_NCANOBS] [numeric](13, 3) NOT NULL,
	[FA2_NPREOBS] [numeric](18, 9) NOT NULL,
	[FA2_NIMPOBS] [numeric](13, 2) NOT NULL,
	[FA2_NCAXPRE] [numeric](13, 3) NOT NULL,
	[FA2_NPRXPRE] [numeric](18, 9) NOT NULL,
	[FA2_CSUCANT] [char](4) NOT NULL,
	[FA2_CDOCANT] [char](2) NOT NULL,
	[FA2_CSERANT] [char](4) NOT NULL,
	[FA2_CNUMANT] [char](11) NOT NULL,
	[FA2_CDATADI] [varchar](12) NOT NULL,
	[FA2_CITEFAC] [varchar](4) NOT NULL,
	[FA2_CCODACT] [char](25) NOT NULL,
	[FA2_CSITACT] [char](1) NOT NULL
 CONSTRAINT [PK_INTDOCELEDET] PRIMARY KEY CLUSTERED 
(
	[FA2_CRUCEMI] ASC,
	[FA2_CCODSUC] ASC,
	[FA2_CTIPDOC] ASC,
	[FA2_CSERDOC] ASC,
	[FA2_CNUMDOC] ASC,
	[FA2_CITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE TBL_DOCELEREF(
	NID_DOCELEREF INT IDENTITY(1,1),
	NU_REFDOCORG VARCHAR(40),
	CO_REFTIPDOC CHAR(2),
	NU_REFNUMDOC VARCHAR(30),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEREF_NID_DOCELEREF PRIMARY KEY (NID_DOCELEREF),
	CONSTRAINT FK_DOCELEREF_DOCELECAB_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TBL_DOCELEDET(
	NID_DOCELEDET INT IDENTITY(1,1),
	NU_DETORDITM VARCHAR(5),
	CO_DETUNDMED VARCHAR(3),
	QT_DETCANITM DECIMAL(12,10),
	CO_DETCODPRO VARCHAR(30),
	CO_DETCOPRSU VARCHAR(8),
	CO_DETCODGS1 VARCHAR(14),
	TX_DETDESITM VARCHAR(500),
	MT_DETVALUNI DECIMAL(12,10),
	MT_DETPREVEN DECIMAL(12,10),
	CO_DETCODPRE CHAR(2),
	MT_DETVALREF DECIMAL(12,10),
	CO_DETCOVARE CHAR(2),
	MT_DETTOTIMP DECIMAL(12,2),
	MT_AFEMONBAS DECIMAL(12,2),
	MT_AFEMONAFE DECIMAL(12,2),
	PO_AFEMONPRC DECIMAL(12,5),
	CO_AFEREASON VARCHAR(2),
	CO_AFECODTRI CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_ISCMONAFE DECIMAL(12,2),
	PO_ISCMONPRC DECIMAL(12,5),
	CO_ISCTIPSIS CHAR(2),
	CO_ISCCODTRI CHAR(4),
	MT_DETVALVEN DECIMAL(12,2),
	NO_DETCARDES VARCHAR(5),
	CO_CARDESREA CHAR(2),
	DE_CARDESFAC DECIMAL(12,5),
	MT_CARDESMON DECIMAL(12,2),
	MT_CDEMONBAS DECIMAL(12,2),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEDET_NID_DOCELEDET PRIMARY KEY (NID_DOCELEDET),
	CONSTRAINT FK_DOCELECAB_DOCELEDET_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TL_PROFACINT(
	NID_PROFACINT INT IDENTITY(1,1),
	CO_ESTPROINT VARCHAR(30),
	NO_ESTPROINT VARCHAR(100),
	CO_TIPPROFAC VARCHAR(30),
	NO_TIPPROFAC VARCHAR(150),
	TX_DESCRIPCI VARCHAR(3000),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_EMIDOCELE INT
	CONSTRAINT PK_PROMIGINT_NID_PROMIGINT PRIMARY KEY (NID_PROFACINT),
	CONSTRAINT FK_PROMIGINT_NID_EMIDOCELE FOREIGN KEY (NID_EMIDOCELE) REFERENCES MAE_EMIDOCELE(NID_EMIDOCELE)
)
GO

CREATE TABLE MAE_DATGENFAC(
	NID_DATGENFAC INT IDENTITY(1,1),
	NO_NOMMAEFAC VARCHAR(150),
	TX_DESMAEFAC VARCHAR(300),
	NO_CAMPOFAC1 VARCHAR(100),
	NO_CAMPOFAC2 VARCHAR(100),
	NO_CAMPOFAC3 VARCHAR(100),
	NO_CAMPOFAC4 VARCHAR(100),
	NO_CAMPOFAC5 VARCHAR(100),
	NO_CAMPOFAC6 VARCHAR(100),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DATGENFAC_NID_DATGENFAC PRIMARY KEY (NID_DATGENFAC)
)
GO

-- INSERCCIÓN DE DATOS
--
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('TIPPROINT', 'Guarda todos los tipos de procesos de la interface', 'MIG', 'Migración', GETDATE(), '0');
GO
--
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'CO', 'Correcto', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EJ', 'Ejecutando', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EX', 'Excepción', GETDATE(), '0');
GO
--
INSERT INTO MAE_EMIDOCELE VALUES('20263019807', 'GRANOTEC PERU SA', '0001', 'ACTIVO', 'HABIDO', '150103', 'Lima', 'Lima', 'Ate', 'AV. LOS INGENIEROS NRO. 112 URB. - SANTA RAQUEL 2DA ETAPA', 'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'comercial', 'SA', 'A123456$', 'FAC0001FAC1', 'FAC0001FAC2', '', 'FACTURA1', 'FACTURA1', NULL, GETDATE(), NULL, '0');
GO
--CREACION DE PROCEDURES

CREATE PROCEDURE SPS_SEG_GETERRINF
AS  
SELECT  
    ERROR_NUMBER() AS NU_ERRNUMBER
    ,ERROR_SEVERITY() AS NO_ERRSERVER
    ,ERROR_STATE() AS NO_ERROSTATE
    ,ERROR_PROCEDURE() AS NO_ERRORPROC
    ,ERROR_LINE() AS NU_ERRORLINE
    ,ERROR_MESSAGE() AS TX_ERRORMESS;  
GO

CREATE PROCEDURE SPS_MAE_EMIDOCELE
AS
BEGIN
	SELECT
		*
	FROM MAE_EMIDOCELE
	WHERE FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPS_TL_PROFACINT_BY_EMIDOCELE(
	@NID_EMIDOCELE INT,
	@CO_ESTPROINT VARCHAR(30),
	@CO_TIPPROFAC VARCHAR(30)
)
AS
BEGIN
	SELECT NID_EMIDOCELE, CO_ESTPROINT, CO_TIPPROFAC
	FROM TL_PROFACINT
	WHERE CO_ESTPROINT = @CO_ESTPROINT
	AND CO_TIPPROFAC = @CO_TIPPROFAC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
	AND FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPI_TL_PROFACINT(
	@CO_TIPPROFAC VARCHAR(30), 
	@CO_ESTPROINT VARCHAR(30), 
	@NID_EMIDOCELE INT
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'IPROFACINT'
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @NO_TIPPROFAC VARCHAR(150),
				@NO_ESTPROINT VARCHAR(150)

		SELECT @NO_TIPPROFAC = TIPPROFAC.NO_CAMPOFAC2
		FROM MAE_DATGENFAC TIPPROFAC
		WHERE TIPPROFAC.NO_NOMMAEFAC = 'TIPPROINT'
		AND TIPPROFAC.NO_CAMPOFAC1 = @CO_TIPPROFAC
		AND TIPPROFAC.FL_REGINACTI = '0'

		SELECT @NO_ESTPROINT = ESTPROINT.NO_CAMPOFAC2
		FROM MAE_DATGENFAC ESTPROINT
		WHERE ESTPROINT.NO_NOMMAEFAC = 'ESTINTFAC'
		AND ESTPROINT.NO_CAMPOFAC1 = @CO_ESTPROINT
		AND ESTPROINT.FL_REGINACTI = '0'

		INSERT INTO TL_PROFACINT(CO_ESTPROINT, NO_ESTPROINT, CO_TIPPROFAC, NO_TIPPROFAC, FE_REGCREACI, NID_EMIDOCELE, TX_DESCRIPCI, FL_REGINACTI)
		SELECT @CO_ESTPROINT, @NO_ESTPROINT, @CO_TIPPROFAC, @NO_TIPPROFAC, GETDATE(), @NID_EMIDOCELE, 'Apertura de Nuevo Proceso en ejecución','0'
		
		
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION @NO_TRANSNAME;
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPU_TL_PROFACINT(
	@CO_TIPPROFAC VARCHAR(30), 
	@CO_ESTPROINT VARCHAR(30), 
	@NID_EMIDOCELE INT,
	@TX_DESCRIPCI VARCHAR(3000) = NULL
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'UPROFACINT'
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @NO_ESTPROINT VARCHAR(150)

		SELECT @NO_ESTPROINT = ESTPROINT.NO_CAMPOFAC2
			FROM MAE_DATGENFAC ESTPROINT
			WHERE ESTPROINT.NO_NOMMAEFAC = 'ESTINTFAC'
			AND ESTPROINT.NO_CAMPOFAC1 = @CO_ESTPROINT
			AND ESTPROINT.FL_REGINACTI = '0'

		UPDATE TL_PROFACINT
			SET CO_ESTPROINT = @CO_ESTPROINT,
				NO_ESTPROINT = @NO_ESTPROINT,
				TX_DESCRIPCI = 
					CASE
						WHEN ISNULL(@TX_DESCRIPCI, '') <> '' THEN @TX_DESCRIPCI
						WHEN @CO_ESTPROINT = 'EX'  THEN  'Proceso Finalizado con errores'
						WHEN @CO_ESTPROINT = 'CO' THEN 'Proceso Finalizado correctamente'
					END
		WHERE NID_EMIDOCELE = @NID_EMIDOCELE
		AND CO_TIPPROFAC = @CO_TIPPROFAC
		AND CO_ESTPROINT = 'EJ'
		AND FL_REGINACTI = '0'
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPI_TBL_DOCELECD(
	@XM_EMIDOCELE XML,
	@XM_DOCELECAB XML,
	@XM_DOCELEDET XML
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'IDOCELECD'
	--BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @I_DOCEMI INT ,@I_DOCCAB INT, @I_DOCDET INT
		--Emisor
		-- Cabecera
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCEMI OUTPUT, @XM_EMIDOCELE;
		SELECT	  *
		INTO #TMP_EMIDOCELE
		FROM  OPENXML (@I_DOCEMI, '/BEMaeemiele',2)
			WITH(
				nid_maeemiele INT,   
				nu_eminumruc VARCHAR(11),
				no_emirazsoc VARCHAR(50),
				no_estemiele VARCHAR(30),
				no_conemiele VARCHAR(50),
				no_emiubigeo CHAR(6),
				no_emidepart VARCHAR(50),
				no_emiprovin VARCHAR(50),
				no_emidistri VARCHAR(50),
				no_emidirfis VARCHAR(500),
				no_bastipbas VARCHAR(50),
				no_basnomsrv VARCHAR(150),
				no_basnombas VARCHAR(50),
				no_basusrbas VARCHAR(50),
				no_basusrpas VARCHAR(100),
				no_tabfaccab VARCHAR(50),
				no_tabfacdet VARCHAR(50),
				no_rutcerdig VARCHAR(800),
				fe_regcreaci DATETIME,   
				fe_regmodifi DATETIME,   
				fl_reginacti CHAR(1) 
			)
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCCAB OUTPUT, @XM_DOCELECAB;
		SELECT    *  
		INTO #TMP_DOCELECAB
		FROM OPENXML (@I_DOCCAB, '/BEDoccabcli',2)
		 WITH (fa1_ccodsuc char(4),
				fa1_ctipdoc char(2),
				fa1_cserdoc char(4),
				fa1_cnumdoc char(11),
				fa1_dfecdoc char(8),
				fa1_dfecven char(8),
				fa1_ccodcli varchar(18),
				fa1_cnomcli varchar(80),
				fa1_cruccli varchar(18),
				fa1_cdircli varchar(160),
				fa1_cforven nchar(5),
				fa1_ccodven nchar(5),
				fa1_ccodve2 nchar(5),
				fa1_ctgdore char(2),
				fa1_csedore char(4),
				fa1_cnudore varchar(20),
				fa1_ctgdor2 char(2),
				fa1_cnudor2 varchar(20),
				fa1_ctipope char(2),
				fa1_ccodalm char(4),
				fa1_ccencos char(12),
				fa1_cglosa1 varchar(100),
				fa1_cglosa2 varchar(100),
				fa1_ccodmon char(2),
				fa1_ntipcam numeric(9, 3),
				fa1_nimport numeric(15, 2),
				fa1_nporde1 numeric(5, 2),
				fa1_nporde2 numeric(5, 2),
				fa1_nporde3 numeric(5, 2),
				fa1_cdirecc char(80),
				fa1_cdebhab char(1),
				fa1_cstock char(1),
				fa1_cestado char(1),
				fa1_cusucre char(10),
				fa1_dfeccre char(8),
				fa1_cusumod char(10),
				fa1_dfecmod char(8),
				fa1_cdocori char(2),
				fa1_cdocate char(2),
				fa1_ccodubi char(8),
				fa1_ctgpais char(5),
				fa1_csudore char(4),
				fa1_csucate char(4),
				fa1_cnumate char(15),
				fa1_chorcre char(5),
				fa1_chormod char(5),
				fa1_cdirfis varchar(160),
				fa1_cortsuc char(4),
				fa1_corttal char(4),
				fa1_cortnum char(11),
				fa1_ccodcaj char(4),
				fa1_cflacan char(1),
				fa1_ctgdor3 char(2),
				fa1_cnudor3 varchar(20),
				fa1_cflamas char(1),
				fa1_nimpper numeric(13, 2),
				fa1_nporper numeric(10, 2),
				fa1_cflacct char(1),
				fa1_cortveh char(18),
				fa1_dfecpro char(8),
				fa1_nporigv numeric(4, 2),
				fa1_ccodtra char(8),
				fa1_cnomtra varchar(50),
				fa1_ccodveh char(8),
				fa1_ccodfer char(8),
				fa1_dfecref char(8),
				fa1_ccoddir char(4),
				fa1_ctipmov char(1),
				fa1_cglosa3 varchar(50),
				fa1_cdepori varchar(6),
				fa1_cdepdes varchar(6),
				fa1_ccodper char(8),
				fa1_ckeyint char(17),
				existe char(1),
				nuevo char(7),
				fa1_ccodsur varchar(4),
				fa1_npercmn numeric(13, 2),
				fa1_npercus numeric(13, 2),
				fa1_nnumimp numeric(3, 0),
				fa1_cfladet char(1),
				fa1_cflaant char(1),
				fa1_nimpant numeric(15, 2),
				fa1_nsalant numeric(15, 2),
				fa1_ccodref char(8),
				fa1_cdatadi varchar(12),
				fa1_ccodcob varchar(8),
				fa1_ccodsub char(4),
				fa1_ccompro char(8),
				fa1_canocom char(4),
				fa1_dfecanu char(8),
				fa1_ccoddet char(5),
				fa1_nportas numeric(12, 2),
				fa1_cmonant char(3),
				fa1_nsumapl numeric(15, 2),
				fa1_cod_estado_sunat int,
				fa1_mensaje_sunat varchar(500),
				fa1_estado_envio int,
				fa1_xml varchar(250),
				fa1_cdr varchar(250),
				fa1_pdf varchar(250),
				fa1_dfecdoc9 datetime);
		EXEC SP_XML_PREPAREDOCUMENT @I_DOCDET OUTPUT, @XM_DOCELEDET;
		SELECT	  *
		INTO #TMP_DOCELEDET
		FROM  OPENXML (@I_DOCDET, '/ArrayOfBEDocdetcli/BEDocdetcli',2)
			WITH(fa2_ccodsuc char(4),
					fa2_ctipdoc char(2),
					fa2_cserdoc char(4),
					fa2_cnumdoc char(11),
					fa2_citem char(4),
					fa2_ccodart char(25),
					fa2_cnomart char(60),
					fa2_cuniart nchar(3),
					fa2_ncantid numeric(13, 3),
					fa2_nprecio numeric(18, 9),
					fa2_npreuni numeric(18, 9),
					fa2_nprunmn numeric(18, 9),
					fa2_nprunus numeric(18, 9),
					fa2_nprsigv numeric(18, 9),
					fa2_ccodalm char(8),
					fa2_ccodmon char(2),
					fa2_ntipcam numeric(7, 3),
					fa2_nporde1 numeric(5, 2),
					fa2_nimpde1 numeric(12, 2),
					fa2_nporde2 numeric(5, 2),
					fa2_nimpde2 numeric(10, 2),
					fa2_nporde3 numeric(5, 2),
					fa2_nimpde3 numeric(10, 2),
					fa2_ntotdes numeric(10, 2),
					fa2_nporigv numeric(5, 2),
					fa2_nimpigv numeric(13, 2),
					fa2_nimport numeric(13, 2),
					fa2_nimpomn numeric(13, 2),
					fa2_nimpous numeric(13, 2),
					fa2_niigvmn numeric(13, 2),
					fa2_niigvus numeric(13, 2),
					fa2_cstock char(1),
					fa2_cestado char(1),
					fa2_cusucre char(10),
					fa2_dfeccre char(8),
					fa2_cusumod char(10),
					fa2_dfecmod char(8),
					fa2_ncostmn numeric(18, 9),
					fa2_ncostus numeric(18, 9),
					fa2_ncanate numeric(13, 3),
					fa2_cdocate char(2),
					fa2_csucate char(4),
					fa2_cnumate char(15),
					fa2_cflakit char(1),
					fa2_ccodcaj char(4),
					fa2_nporper numeric(10, 2),
					fa2_nimpper numeric(13, 2),
					fa2_npercmn numeric(13, 2),
					fa2_npercus numeric(13, 2),
					fa2_ccodar2 varchar(25),
					fa2_calmref char(4),
					fa2_cflaate char(1),
					fa2_npesart numeric(10, 2),
					existe char(1),
					nuevo char(7),
					fa2_ncanbul numeric(5, 0),
					fa2_npesbul numeric(10, 2),
					fa2_ncanti2 numeric(16, 6),
					fa2_ncanti3 numeric(13, 3),
					fa2_ncanobs numeric(13, 3),
					fa2_npreobs numeric(18, 9),
					fa2_nimpobs numeric(13, 2),
					fa2_ncaxpre numeric(13, 3),
					fa2_nprxpre numeric(18, 9),
					fa2_csucant char(4),
					fa2_cdocant char(2),
					fa2_cserant char(4),
					fa2_cnumant char(11),
					fa2_cdatadi varchar(12),
					fa2_citefac varchar(4),
					fa2_ccodact char(25),
					fa2_csitact char(1));

		--Insertando en tablas cabecera y detalle
		INSERT INTO INT_DOCELECAB
		SELECT emi.nu_eminumruc, cab.*
		FROM #TMP_EMIDOCELE emi
		CROSS JOIN #TMP_DOCELECAB cab

		INSERT INTO INT_DOCELEDET
		SELECT emi.nu_eminumruc, det.*
		FROM #TMP_EMIDOCELE emi
		CROSS JOIN #TMP_DOCELEDET det
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION @NO_TRANSNAME;
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO

CREATE PROCEDURE SPS_GET_CORRELATIVO_MASIVOS(
	@NID_EMIDOCELE INT,
	@CO_DOCTIPDOC CHAR(2)
)
AS
BEGIN
	SELECT (ISNULL(MAX(NU_DOCACTUAL),0) + 1) AS CORRELATIVO FROM MAE_CFGSEREMI
	WHERE CONVERT(VARCHAR(10),FE_REGMODIFI,103) = CONVERT(VARCHAR(10),GETDATE(),103)
	AND CO_DOCTIPDOC = @CO_DOCTIPDOC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
END
GO

CREATE PROCEDURE SPS_SET_CORRELATIVO_MASIVOS(
	@NID_EMIDOCELE INT,
	@CO_DOCTIPDOC CHAR(2),
	@NU_DOCNEOCOR INT
)
AS
BEGIN
	UPDATE MAE_CFGSEREMI
	SET NU_DOCACTUAL = @NU_DOCNEOCOR,
	FE_REGMODIFI = GETDATE()
	WHERE CO_DOCTIPDOC = @CO_DOCTIPDOC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
END
GO

SELECT * FROM INT_DOCELECAB
SELECT * FROM INT_DOCELEDET
